From No.Reply@garmin.com Wed May  3 10:52:27 2017
Return-Path: <No.Reply@garmin.com>
X-Spam-Checker-Version: SpamAssassin 3.4.1 (2015-04-28) on mezger.macnugget.org
X-Spam-Level: 
X-Spam-Status: No, score=-4.1 required=5.0 tests=BAYES_00,DKIM_SIGNED,
	DKIM_VALID,DKIM_VALID_AU,HTML_MESSAGE,MIME_HTML_ONLY,RCVD_IN_DNSWL_NONE,
	RCVD_IN_MSPIKE_H2,SPF_HELO_PASS,SPF_PASS autolearn=ham autolearn_force=no
	version=3.4.1
X-Original-To: nugget@macnugget.org
Delivered-To: nugget@macnugget.org
Received-SPF: Pass (sender SPF authorized) identity=mailfrom; client-ip=104.47.32.110; helo=nam01-sn1-obe.outbound.protection.outlook.com; envelope-from=no.reply@garmin.com; receiver=nugget@macnugget.org 
Received: from NAM01-SN1-obe.outbound.protection.outlook.com (mail-sn1nam01on0110.outbound.protection.outlook.com [104.47.32.110])
	(using TLSv1 with cipher ECDHE-RSA-AES256-SHA (256/256 bits))
	(Client CN "mail.protection.outlook.com", Issuer "Microsoft IT SSL SHA2" (not verified))
	by mezger.macnugget.org (Postfix) with ESMTPS id 879A9109278
	for <nugget@macnugget.org>; Wed,  3 May 2017 15:52:26 +0000 (UTC)
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=garmin.com;
 s=selector1; h=From:Date:Subject:Message-ID:Content-Type:MIME-Version;
 bh=Dl3k6D65OzZ3fWAUvmTpK7nY612TPtXuB00TxWLBOzc=;
 b=IQMPtBdTJ2+lM5Ye3ztOhiqQBd1z5FMbCxgziQn2T1pVxOK49UUBlkv4NbLW2k9uEZYwFyr3nTGEOLMin6nCZBxRCqGIfZbT3xfNF6mSbqXIifCT78YMT2WFsXkN5ZLHdRYdq6GzohpOJCfjHFHQ7QhxCKQNQUVuLgvua8muhNI=
Received: from CY1PR04CA0008.namprd04.prod.outlook.com (10.166.187.18) by
 BY2PR04MB863.namprd04.prod.outlook.com (10.242.40.151) with Microsoft SMTP
 Server (version=TLS1_2, cipher=TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256_P256) id
 15.1.1047.13; Wed, 3 May 2017 15:52:18 +0000
Received: from BN1AFFO11OLC001.protection.gbl (2a01:111:f400:7c10::141) by
 CY1PR04CA0008.outlook.office365.com (2a01:111:e400:c5a5::18) with Microsoft
 SMTP Server (version=TLS1_2,
 cipher=TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256_P256) id 15.1.1075.11 via
 Frontend Transport; Wed, 3 May 2017 15:52:18 +0000
Authentication-Results: spf=pass (sender IP is 204.77.163.247)
 smtp.mailfrom=garmin.com; macnugget.org; dkim=none (message not signed)
 header.d=none;macnugget.org; dmarc=bestguesspass action=none
 header.from=garmin.com;
Received-SPF: Pass (protection.outlook.com: domain of garmin.com designates
 204.77.163.247 as permitted sender) receiver=protection.outlook.com;
 client-ip=204.77.163.247; helo=edgetransport.garmin.com;
Received: from edgetransport.garmin.com (204.77.163.247) by
 BN1AFFO11OLC001.mail.protection.outlook.com (10.58.53.72) with Microsoft SMTP
 Server (version=TLS1_0, cipher=TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA_P384) id
 15.1.1047.9 via Frontend Transport; Wed, 3 May 2017 15:52:17 +0000
Received: from olaxpa-itwgems07.garmin.com (172.25.66.34) by
 edgetransport.garmin.com (192.168.18.220) with Microsoft SMTP Server id
 14.3.319.2; Wed, 3 May 2017 10:51:15 -0500
From: Garmin <noreply@garmin.com>
To: <nugget@macnugget.org>
Message-ID: <843262678.1308481493826680839.JavaMail.tomcat@smtp.garmin.com>
Subject: =?UTF-8?Q?________Watch_David_McNett=E2=80=99s_live_activity_now!=0A?=
MIME-Version: 1.0
Content-Type: text/html; charset="UTF-8"
Content-Transfer-Encoding: 7bit
Date: Wed, 3 May 2017 10:51:15 -0500
X-EOPAttributedMessage: 0
X-MS-Office365-Filtering-HT: Tenant
X-Forefront-Antispam-Report:
	CIP:204.77.163.247;IPV:NLI;CTRY:US;EFV:NLI;SFV:NSPM;SFS:(10019020)(6029001)(39840400002)(39860400002)(39450400003)(39850400002)(39400400002)(39410400002)(2980300002)(438002)(199003)(189002)(9170700003)(77096006)(2351001)(64544003)(54356999)(861006)(50466002)(110136004)(106466001)(7066003)(5660300001)(6916009)(38730400002)(53386004)(7906003)(104016004)(189998001)(53416004)(356003)(23676002)(230700001)(2906002)(8936002)(307094003)(54896002)(5820100001)(81166006)(50986999)(19618635001)(226693001)(733005)(81156014)(6306002)(23846002)(606005)(236005)(53936002)(86816001)(508600001);DIR:OUT;SFP:1102;SCL:1;SRVR:BY2PR04MB863;H:edgetransport.garmin.com;FPR:;SPF:Pass;MLV:ovrnspm;A:1;MX:1;PTR:InfoDomainNonexistent;LANG:en;
X-Microsoft-Exchange-Diagnostics: 1;BN1AFFO11OLC001;1:n6NgabRYYmQQctCZCUBZqrjNI4iwcQqlTo8iPDw+OcU7SI3Utr8tBUVzyAQglcs0VHRMS6Xdla4jUwMH03TMFPgE115VA03Q4XSCik8Jz0qQ/DQWFzWzm+zgtYQf2brw7kVaT79+CsZ5UpX+loT557qNhh59eItvbEBXeTdnNr6utY9BF1ZWyMlIfTGvpSU+0HijweqzlwDZh9nikIfygMgVvLTtDkJe8KtUV5U1QN5dBVF26HfEz6fRTtAYvsgTdnO0yYZTcaYGuFM+M0B+uDNZMt5G5Arz+xo1dHaLjEVQuGzcu7l4TfHgEKLf4oMbAvuCwHDKrXOs3lrut2spbNdvJfdeBzCW31kzvQp9fCFvNEUNuInlAU9pFfFkbPC3ay1uATXjL7SB2U2vrJfsRwkPxrgIzAd508KbqphbNcuzkTmL5ZUSbrChGEeWlfltmR1H1FXYkg0bykhg+1uHXYp6oXbVQZZW/CZnxHWDoaLTrO3sB6NoZY76nAhte/GyEELZcdgTOHgUXtn85r1NsKFXwyc2T3bMmFuZbAGylS8=
X-MS-PublicTrafficType: Email
X-MS-Office365-Filtering-Correlation-Id: 907ffa05-4aa2-4b0b-c4a8-08d4923c6079
X-Microsoft-Antispam:
	UriScan:;BCL:0;PCL:0;RULEID:(22001)(8251501002)(2017030254075)(201703131423075)(201703031133081);SRVR:BY2PR04MB863;
X-Microsoft-Exchange-Diagnostics:
	1;BY2PR04MB863;3:aPH57yDiJ1iAWqvDiwXz7hT3K2NocguJ7Gsl47DA1ax56SflwJC9kPt9mzIsglyqg4kZIk4etJywtJxPMdyElmUsyl3u32GCx7vcO2qsCVbfIVlsCa/CbzFYRo/VdBz86C7MC8Ur7pqoNhxNhDJLqGXE/mWsuIrqgDhrOzmAOl9Yn7ms5SZW8XIIvUt6/PW30ORtp839VkP8q3GEPfJDZ3rySum9z7nrhmZD/UYFFrx6T6U1B3c/9+l8fFWzlCpKL8Ura55NdqBh1N3uIrUQXoiH0j2+hzqQCEmyXigi7NJ43rKfC3SfXx7+RFhIoqpyVavmzJ4rxHIyxPDMXEbrK0aUET9EEM9lm8hlxyt+HFlO13QZ4/Tm1hsLf8V9/XzBqgb0l75eKGhomLXi0olEtJMxjSFy5GLP7cR6c4KJdf27NvS78MY44ara/jYgmBGduf9EcGoPYVRHbWjDu4bn/ix+ZyHc6b23IMosZii7yJCRzj0qof/jnbgsAP5qXnM6
X-Microsoft-Exchange-Diagnostics:
	1;BY2PR04MB863;25:eQc7wO2ng64oBSd1X3r5c0Ss/Sns53DuC59gYLbfEnA4dc2LSMl9rIpAacxS+k5tYVbjSao8rgI4CYbxAS2IhZQ/zx9timeLv3D438D6sr4ydauHH69G2sBvbgSWV2yLAxj0I0FwLy+ixco0XpK6N+5uMmZmKhsE5aly1WAO1AOqdWJiWWjO4fgodJ4d6TKb8JCCF1aPnFvV97C/6l82lMmJIL9n+igIZgDFheUnsqN5qQZQZKWz3ztMvBkAqKRcNmkRgkjS54+FEcwR4/rAHBSPSzgodDAI/IsCIhLUuWUFgdMNNls+w4oayj0r6bLoqmmnEAIgV6PUCx4IGtnhq+J6VDtTJftwemOXPGe3+jHibFpfuoy6K6bI8lCb6gXpS0GJHsyJsKbL0fj1mpTZceV0TabixpntR+OsqvEQExKzMf+SWp0LDvFllAuR+pW+pv2hHRSDSTsEfkFUgblu+A==;31:6OVbUwj5fJFc7aan/W746ReFpgVmR8NXkPBchpsBTEpyYcRA2ASqLa7ZHx15vl1y6SgH8JIvqkExpdALyQjqR97Sdo/hlmGUIZp+uk3bmz3i9EP6t2VNIKJPmYDshrsl/AxlDJGiCQeoyMduQFSIR8Vrg8Tlpwv4adyc97ED8wHYdUxkNZb53MQ4BUJhFIv+xaT8jngKekH6oIIpENvS44g8A5/wqylPfei8OM4dipqEZ6QRh1FCWjG+9bUwyHZTpbp+yCVVu32PsbsDAwpXTQ==
X-Microsoft-Exchange-Diagnostics:
	1;BY2PR04MB863;20:XwhjqChSrtCzFGuYlo1aQRarNaj7q7dxF8vgqyknuXCUkZKQjLeqc8WdsH2viGH25YgbBaxfYaMLWLzz8r4EIges2+9Nvp6LRZVFGWqX2V+LnlRh1ZZdwSpYRcOJL6zyrW+fWU2To6RdOFdgfczIl7ha6ThS4MRJ8NmhWDgUK7+PyF6ziT5J2u5h3NhVwUVjBOkO6I91ZaSRqrJGDXkbE68ZjbBpMwvQWZNqzWbnmz6CQByDeMICkmoRFG+tRvRfkL9yKzvC/TgK+ifecer4v+3wSg0Q+l2/p0iFOq6XzqBBrzT+c927cLxJ2xDUH/0L3gJaI58wiQjbm5+hcj3AT+M9y8BV/5mNyw6Zb+XTwoTi4/KYumm90DgaSTGSsdJ5lciduKS8HtK/ihLb9M0IfsJjhO9bjtbnjkbvrc7nGE7eo6/UasoA2NZrr2qCR0e76A7Tzr829vNQ2v3DdijCi6Dvnh5LT85yp9VkpOoe1MBRNU9cMDF1KWFELqFsOFZj
X-Microsoft-Antispam-PRVS:
	<BY2PR04MB863581359D302F293631F9CF6160@BY2PR04MB863.namprd04.prod.outlook.com>
X-Exchange-Antispam-Report-Test:
	UriScan:(192374486261705)(139250961331683)(35750212558895)(25815076450767)(21532816269658)(210672237334638);
X-Exchange-Antispam-Report-CFA-Test:
	BCL:0;PCL:0;RULEID:(6040450)(601004)(2401047)(13017025)(13023025)(13018025)(13024025)(8121501046)(13015025)(5005006)(3002001)(10201501046)(93006095)(93004095)(6055026)(6041248)(20161123562025)(20161123560025)(201703131423075)(201702281528075)(201703061421075)(20161123555025)(20161123564025)(6072148);SRVR:BY2PR04MB863;BCL:0;PCL:0;RULEID:;SRVR:BY2PR04MB863;
X-Microsoft-Exchange-Diagnostics:
	=?utf-8?B?MTtCWTJQUjA0TUI4NjM7NDpOVVVjTnY4V1ROY1ZrS2kzOGFuVzRpUHc1YlJU?=
 =?utf-8?B?UFloS1dLUVBySlU1aXZSWTR4VjNTSkVZQkwwaVJ4cEt0dUhRUVJ0QUhNVjho?=
 =?utf-8?B?ZkVCUENiWEJ2NEdsdHVseTgrWHdHZnBqcmRaZmRIRE54MkpXQ2p0WUszV2lp?=
 =?utf-8?B?TzREVDg3Y0tjYXNrcVNnL2k1VEhvK1lQY2hLdVBJWHpWNmh6Z0hOc0pQdVhj?=
 =?utf-8?B?ZjdPRkVIWnhFV1E5YzNhWEswY2pjcmI3SWV2Rk1BSVZ3UnVTVUIwNVJoYW0v?=
 =?utf-8?B?dW83UVllVVJ6UjNqcG9PZ3VRL1JLRkJ2WGRjQlNOcjRLbVBER0JraWJ4eEsv?=
 =?utf-8?B?QUVYa1hSVDdDd1p0cVlTY2M1ZzhxUkJaSnJZNTkxeVVEdDRIblJRVnZvMXJH?=
 =?utf-8?B?akk1Z2EyeC90MGc4Sy9oQ05mMzhEN0dodktqQng5ZTdCTHc2VTRVWlV6SzFW?=
 =?utf-8?B?T1hZMnl1dTUyTWRzb2VETklleStoQmJKNEtBOVVnMWhzY2J5SjAxVzIyTnZo?=
 =?utf-8?B?ZnZIVVBFK1NmYURmaytlSkJYeHc2ai85bEJLWjVCaEpuREY0azZQS2ZpV2xv?=
 =?utf-8?B?a1h2Y1RJbU5mREJwZUZmUGN0TWJkbWtsMzduQ3JJdE9TUjBReEZOWUR2dVNP?=
 =?utf-8?B?eEdHNUtWMHh0dEpSRExBcW00MWkvWW4weDBDbzhTKzBBb3ZwMVNQczk1VDlI?=
 =?utf-8?B?UTFhaWNOUkRQUTFGWDV1VzZtRU5LR1M4dmNMNkQrSERseWxYZGVqemFpUmhJ?=
 =?utf-8?B?dnJXaXQwc0FIZzA4dm5jUTJIcUFBYk9rV3RtOGtrSVplaS9nd3FuamtUMWxs?=
 =?utf-8?B?czRVUzZNYjRLQnRNQnpQOW1QUDM4Z0E1Z1RyZTNjMjNzSlpna0lPcTFqc1B6?=
 =?utf-8?B?Y0U4RDdqNFBxcFFVQm9hZXZkYXpZZzhrRndvRlk4U0J1YUJBMjlBZUIvejBJ?=
 =?utf-8?B?TUI4RUZFUSt2Uit0QU1lNCs0T3lPbmt3bUhrZTdHdmFSMWhwd3lmTktsTi9w?=
 =?utf-8?B?eFNrZTBIUWlzVTJ2bHdLRlQ3NUp5L3BlZytPRzYwbjE5dEpEZzRjOGRuc1lU?=
 =?utf-8?B?S3M0VUdxT2ZrSDVKZUhvcjIwWlZUSGQ3ZW9EM0RUMW5kTnNPMSs1Qlp5dnFE?=
 =?utf-8?B?em1SVzVjU0F1SVZQb3JBT2ZIcmtkQ0hXNHdFd0pXakF6NXgxOE1sWk5pNlFO?=
 =?utf-8?B?MkVLMXUwYytURlZzQnZMK1BZMk4xa1NicERaTk1UUmxMS3cyeWdvdG51UVFu?=
 =?utf-8?B?YnBJOGdOaUYwZHUvT2R0RmhqUW9nRlAvNENuU1IzODlBSGlWTDZUZFk0ZWFH?=
 =?utf-8?B?SzRLM0JOd25TYXFMOWVmQk1INEt0RUFIN0poWWwzMnNKK2NBcGZ0R01rUWJG?=
 =?utf-8?B?R0NFa1E1MHYvV0lzVDVxSHR5RnFjTjQyeVI4WmRMS0lBUDR4eDMzdXlxSlVu?=
 =?utf-8?Q?bEu0=3D?=
X-Forefront-PRVS: 029651C7A1
X-Microsoft-Exchange-Diagnostics:
	=?utf-8?B?MTtCWTJQUjA0TUI4NjM7MjM6UzdWU2l2L1Z1Y2tvWnJLc3h3Y2lOaW1SZ2I1?=
 =?utf-8?B?QVhNUWNTSW5nMmxzd0s3YXdYM1crTFI3bUgzT1V5TUY1dVdGeUV1TFVDcWRP?=
 =?utf-8?B?TXBaNUNkSzRtcHZIWnVWcGFHWlBhb2dlU3hzcmtSSitrTUFZZ2twcktlY1RB?=
 =?utf-8?B?aERXQlkrQmZTQnlmLzUzTUVaN1d1VFZCT0lNS1hnbEVGd2MwclBzQTV5K0Ix?=
 =?utf-8?B?MDFXcW1tR0RDbTNCcDErZXVYOXlsSmwyTC9lQTdPZFhOOVVwemQzMS80WmJy?=
 =?utf-8?B?Z0JMVE5mcUhCR0czTWRrM2dhTnJ6V0gxUFpyRXUzTW1DRXJMbDdGY040aE9s?=
 =?utf-8?B?QzdSZ1Z4YkUwZUEwRzJWa0lvVFVKYUFUVjJTQXdYRUxzZjJSWC9jRkFiVmxa?=
 =?utf-8?B?MFl0a0lub1NxcklwZVhTOFRycW13V21MeFZzc244dlVtbEtXdk9VRTRpK2Vn?=
 =?utf-8?B?b0l2anY4V1BmS0doZk1Dc1NRbHVkSVRTNnpkS1VBVlhoSkRleGtYVGQzUXhQ?=
 =?utf-8?B?SVN0bDlHMEcrbkMxSE9xSHcvSHhRQjZwRzI0SFR0K1lPaUd5WUc5UHpYZjQ1?=
 =?utf-8?B?QkNVVllKVnAyK0lJaXNpUUxZUXMzQjBoTG9Da2hlRU9vYmpZL3lGWm1VaXBS?=
 =?utf-8?B?TWgrSW93ZWFlZC84RWJtT2Uva0VGc2ZpQmloWnFvSjFXaG1HTmFHbW91dWNj?=
 =?utf-8?B?ZTYrK0xMYkNtZUNaZlVzNm4xR3VMM2FhRHhjMmNFd0haTVZTMFJMU1B3QVB0?=
 =?utf-8?B?dmkwR2djTFU2aHN0WW1iSy85UG5sVUNnV0JMbUUxNlpnZUtQRVpSNWVoRmFr?=
 =?utf-8?B?dFBEakJPTkI4L1VXWnBCWE0wTkpxVjc0elN5WE00TnkzT0ZKd2tWMmw2Wi85?=
 =?utf-8?B?MmlURW15SnoyZ3lEMGNmZHo0S1Y2ekZ3UWhsQmdpUG84ZHVhTFd2aTNEWkw4?=
 =?utf-8?B?NE02TW1mdWVpb1ZMZ0VFMmkvQXoyeVNSTnExVG9wcTZacXJnQzBFU3JHMlE2?=
 =?utf-8?B?N3RuZWZiR3VUVzEvY2prMTVvNjBISDM3UUZseHYwSUJEVWthUDFKZTJBVVQ3?=
 =?utf-8?B?M29sWDA5Q2pWOEVoaXF2dkg4My9WaThGYXNycmFPRE9xaTVsZGkyQ0Yycmdy?=
 =?utf-8?B?VVljQ3FPK1d6OXhCRlZYdExKQVFMTWZHeDFIbjlxcUswM2gzcjdZM0xMWFZL?=
 =?utf-8?B?eUxTbjMzd3pXWG5NMXI1cWxkZkVXWFFzdm9IcWJxckw2QkJFQVQ1amVMY29K?=
 =?utf-8?B?ZHhpSDB0QzhYeGJRdmdrbVdwcXBtMlVnVldVQU1qWmRIMi80aE53ZTBJazg3?=
 =?utf-8?B?dEU2ODM4OGgrWkZJWDl4b2tkelRyeU1NWVV0Ym01cmpFVVJlNjhMbzNoUXFE?=
 =?utf-8?B?bExSa1JOZS9iNjFNdm8xbXBML1p5Snkvd3gwaklQTytnSWVTbXFNWW5USGxz?=
 =?utf-8?B?OXdpcDYwbFJzanAzODRPTmN3MWx3NXN3Z3dGTmpNbGQyYnV3dzNFQUJaeml3?=
 =?utf-8?B?VWxva2h2bk9aMUtJZkRhdTlNN2V4azVpMDBJYSttTXh5Y1daTVFXV1RUbVFq?=
 =?utf-8?B?VE1SeS8wWG8wVmVRcHlIcVljQ3dHMlVKM0I1MG1GenJvdG5aTmZDRExpMGhh?=
 =?utf-8?Q?Nioh1C5BpO4OjLaL0gG?=
X-Microsoft-Exchange-Diagnostics:
	1;BY2PR04MB863;6:HJVLjR5Eeym6nadhA308hTNH60w2+IdAswxV8c2ZmB3mq94iMdnd/NxJDc3qEs2ny2cAPEsUQVNlKT553VBrbwVIqDuHVR53HcrzYmiLTPjjOGlhjXq5V175A/S0PdSUPuJpCw2gRw4dmUBsezFPo8iFlK7xSqNVTv/wzNO9Fj/149E0dzKjRY9M0ABKTKASi+p1JJtr7KlknDCFnddvTyaTVEPoRVYhx4nUt3gVbC1pnQ6EEcNWIxlmamvZnCZiP1j3dI6St6XB8Q4Fns36u2Em3Z1b7rBhTGjhhupISHwwq12i2x7C8yqUngj8zcX79rgcuSbnk/XlMgfi0vbH01IwfN2DC4t9MQxqGa/JwCCzvE3fPUbZq8/ACQBPiKbxBCvYxQb0x17MmFO58fJRGvuf22CyN2KKpDbUsqmacjzk8YkxAWGHdPdhG/lOxybDUpTHnLhdjZXVDbor1AldAkIeejRhly4LpNY7t7Ev3kdzXMhPYGqZw7Oo1q1KFfcRzBwpa/IrMMtc04n17aC1ijtDzHcj0Mg4HpEpUVjR24E=;5:F0BS/uhg1ML9800A1y4bQVnLTJww5DQx4SzxqRW6Xd+86Ju0qvFzsIDJ6dhP6oSdx6AF1iNOUFSNqSSzja60/t5WoYJnVdw8Wp/wp/9fncl2Zp2H5txwnIJFY2pKnsLt82NJBMNJBGwXQiN/ejQDTw==;24:usMk9yI3F6v8vIQTskhL6RMH+FTTu+L2YS7KICjp/i01UZ3zkf2cdPUrK6tMHsBraKW9JaNauPRnlw/XRLUsRVHiLw7txMHRhmqVq690kBI=
SpamDiagnosticOutput: 1:99
SpamDiagnosticMetadata: NSPM
X-Microsoft-Exchange-Diagnostics:
	1;BY2PR04MB863;7:1dfyvqcmpePnLWGtn8yoCbVYOngUvjEPOBKTvbefeaR3jeMeil8nn68zBHK7lcuQM1tfQp0HXZkLt7YrqhtGiXcw+1xFOoOHQX1Zg9yQJ6Ip9HQj0EhzHNzO8sjRKPQ/osnBczBN0m+AVCYGUrG+ud19pn/HHpnEqSSfHBDyKwMXx9zzR7XGm0CpKON581t4lO9jIeUApD9PgJQwypGgNCJq7XKSca6m6pkrwk7I68ktYakXc68vLCgRfxQaeI3MLP5Gp5esBc58HzIkPUdNd840FhxbKycI7e/jtlv8QNx2RlpmOpVB/VNikVlOQBEWU23As8jId8zlmm1eRA+mzA==;20:kIwVJaZTMLd8uXM4z9TdrMeoWZXZUFTLX7JGwqJk2DP9jrHjK6jwLG4O1E1DpI59vJ30y+xRjHEQq7FkonVPdHtE2lgna0r6f301+Nj/8x3xY/qZIKGdLsjCpnZc3uGQhyEzfE7ltmLkWY8AeqvUIaRrECChSm6XrxwOqcyizg0=
X-OriginatorOrg: garmin.com
X-MS-Exchange-CrossTenant-OriginalArrivalTime: 03 May 2017 15:52:17.7248
 (UTC)
X-MS-Exchange-CrossTenant-Id: 38d0d425-ba52-4c0a-a03e-2a65c8e82e2d
X-MS-Exchange-CrossTenant-OriginalAttributedTenantConnectingIp: TenantId=38d0d425-ba52-4c0a-a03e-2a65c8e82e2d;Ip=[204.77.163.247];Helo=[edgetransport.garmin.com]
X-MS-Exchange-CrossTenant-FromEntityHeader: HybridOnPrem
X-MS-Exchange-Transport-CrossTenantHeadersStamped: BY2PR04MB863
Content-Length: 11719
Lines: 227






                <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<style type="text/css">
    #outlook a {padding:0;}
    body{width:100% !important; -webkit-text-size-adjust:100%; -ms-text-size-adjust:100%; margin:0; padding:0;}
    .ExternalClass {width:100%;}
    .ExternalClass, .ExternalClass p, .ExternalClass span, .ExternalClass font, .ExternalClass td, .ExternalClass div {line-height: 100%;}
    .wrapperTable {margin:0; padding:0; width:100% !important; line-height: 100% !important;}
    img {outline:none; text-decoration:none;border:none; -ms-interpolation-mode: bicubic;}
    a img {border:none;}
    .image_fix {display:block;}
    p {margin: 0px 0px !important;}
    table td {border-collapse: collapse;}
    table { border-collapse:collapse; mso-table-lspace:0pt; mso-table-rspace:0pt; }
    table[class=full] { width: 100%; clear: both; }
    @media only screen and (max-width: 640px) {
    a[href^="tel"], a[href^="sms"] {
    text-decoration: none;
    color: #ffffff;
    pointer-events: none;
    cursor: default;
    }
    .mobile_link a[href^="tel"], .mobile_link a[href^="sms"] {
    text-decoration: default;
    color: #ffffff !important;
    pointer-events: auto;
    cursor: default;
    }
    table[class="devicewidth-outer"] {width:440px!important;min-width:440px!important;text-align:center!important;}
    table[class="devicewidth-inner"] {width:400px!important;min-width:400px!important;text-align:center!important;}
    table[class="inner-avatar"]      {width:100px!important;min-width:100px!important;text-align:center!important;}
    table[class="inner-message"]     {width:280px!important;min-width:280px!important;text-align:center!important;}
    img[class="bigimage"]            {width:400px!important;min-width:400px!important;height:219px!important;}
    img[class="col2img"]             {width:400px!important;min-width:400px!important;height:258px!important;}
    img[class="image-banner"]        {width:440px!important;min-width:440px!important;height:106px!important;}
    }
    @media only screen and (max-width: 480px) {
    a[href^="tel"], a[href^="sms"] {
    text-decoration: none;
    color: #ffffff;
    pointer-events: none;
    cursor: default;
    }
    .mobile_link a[href^="tel"], .mobile_link a[href^="sms"] {
    text-decoration: default;
    color: #ffffff !important;
    pointer-events: auto;
    cursor: default;
    }
    table[class="devicewidth-outer"] {width:280px!important;min-width:280px!important;text-align:center!important;}
    table[class="devicewidth-inner"] {width:240px!important;min-width:240px!important;text-align:center!important;}
    table[class="inner-avatar"]      {width:240px!important;min-width:240px!important;text-align:center!important;}
    table[class="inner-message"]     {width:240px!important;min-width:240px!important;text-align:center!important;}
    table[class="full-button"]       {width:100%!important;}
    td[class="mobilecenter"]         {text-align:center!important;}
    td[class="title-space"]          {height:20px!important;}
    img[class="col2img"]             {width:260px!important;min-width:260px!important;height:160px!important;}
    img[class="image-banner"]        {width:280px!important;min-width:280px!important;height:68px!important;}
    a[class="full-button"]           {display:block!important;}
    }
</style>
    </head>
<body>
<!--header and body-->
<br>
<!-- Subject -->
<table width="100%" height="12" bgcolor="#0a1f2e" cellpadding="0" cellspacing="0" border="0" class="wrapperTable"> <!-- Hidden Subject wrapper -->
  <tr>
        <td>
            <table width="580" align="center" bgcolor="#0a1f2e" cellpadding="0" cellspacing="0" border="0" style="min-width:580px;" class="devicewidth-outer">
                <tr>
                    <td style="font-family:'Open Sans', 'Lucida Grande', 'Lucida Sans Unicode', Helvetica, Arial, sans-serif; font-size:10px; color:#0a1f2e; text-align:center;">
                        Watch David McNett&rsquo;s live activity now!
                    </td>
                </tr>
            </table>
        </td>
  </tr>
</table>
<!-- Logo Header -->
<table width="100%" bgcolor="#0a1f2e" cellpadding="0" cellspacing="0" border="0" class="wrapperTable"> <!-- Logo wrapper -->
  <tr>
    <td>
      <table width="580" align="center" bgcolor="#0e334c" cellpadding="0" cellspacing="0" border="0" style="min-width:580px;" class="devicewidth-outer"> <!-- Logo content -->
        <tr> <!-- Spacing -->
          <td height="15"></td>
        </tr>
        <tr> <!-- Logo Image -->
          <td style="width:100%;">
            <table width="540" align="center" cellpadding="0" cellspacing="0" border="0" style="min-width:540px;" class="devicewidth-inner">
              <tr>
                <td width="253" height="27" align="left">

                                      <a target="_blank" href="http://connect.garmin.com">
                        <img width="253" height="27" border="0" alt="Garmin Connect" style="display:block; border:none; outline:none; text-decoration:none; width:253px; height:27px" src="http://static.garmincdn.com/com.garmin.connect/ui/images/logo-connect.png">
                    </a>
                  
                </td>
              </tr>
            </table>
          </td>
        </tr>
        <tr> <!-- Spacing -->
          <td height="15" style="width:100%;"></td>
        </tr>
      </table>
      <table width="580" align="center" bgcolor="#fafafa" cellpadding="0" cellspacing="0" border="0" style="min-width:580px;" class="devicewidth-outer"> <!-- Logo content -->
        <tr> <!-- Spacing -->
          <td height="32" style="width:100%;"></td>
        </tr>
      </table>
    </td>
  </tr>
</table>
<table width="100%" bgcolor="#0a1f2e" cellpadding="0" cellspacing="0" border="0" class="wrapperTable"> <!-- Avatar & Message wrapper -->
  <tr>
    <td>
      <table width="580" align="center" bgcolor="#fafafa" cellpadding="0" cellspacing="0" border="0" style="min-width:580px;" class="devicewidth-outer"> <!-- Head Title Content -->
        <tr> <!-- Head Title -->
          <td>
            <table width="540" align="center" cellpadding="0" cellspacing="0" border="0" style="min-width:540px;" class="devicewidth-inner">
              <tr>
                <td style="font-family:'Open Sans', 'Lucida Grande', 'Lucida Sans Unicode', Helvetica, Arial, sans-serif; font-size:18px; color:#222222; text-align:left; line-height:120%;">
                  An invitation from David McNett
                </td>
              </tr>
            </table>
          </td>
        </tr>
        <tr> <!-- Spacing -->
          <td height="28" class="title-space"></td>
        </tr>
      </table>
    </td>
  </tr>
</table>
<table width="100%" bgcolor="#0a1f2e" cellpadding="0" cellspacing="0" border="0" class="wrapperTable"> <!-- Avatar & Message wrapper -->
  <tr>
    <td>
      <table width="580" align="center" bgcolor="#fafafa" cellpadding="0" cellspacing="0" border="0" style="min-width:580px;" class="devicewidth-outer"> <!-- Avatar & Message content -->
        <tr> <!-- Avatar & Message -->
          <td>
            <table width="540" align="center" cellpadding="0" cellspacing="0" border="0" style="min-width:540px;" class="devicewidth-inner">
              <tr>
                <td>
                  <table width="516" align="right" cellpadding="0" cellspacing="0" border="0" style="min-width:516px;" class="inner-message"> <!-- Message -->
                    <tr> <!-- Comment -->
                      <td style="font-family:'Open Sans', 'Lucida Grande', 'Lucida Sans Unicode', Helvetica, Arial, sans-serif; font-size:14px; color:#222222; text-align:left; line-height:150%;">
                        You&rsquo;re invited to watch my live activity &ldquo;Last Taper Run.&rdquo; Follow my location and workout stats.
                      </td>
                    </tr>
                    <tr> <!-- Spacing -->
                      <td height="24"></td>
                    </tr>
                    <tr> <!-- Button -->
                      <td>
                        <table cellpadding="0" cellspacing="0" border="0" class="full-button">
                          <tr>
                            <td width="100%" align="left" style="-webkit-border-radius:10px; -moz-border-radius:10px; border-radius:10px; background-color:#11a9ed; box-shadow:0 3px 0 0 #0c7cad; text-align:center; padding-top:8px; padding-right:20px; padding-bottom:8px; padding-left:20px;" class="full-button">
                              <a href="http://livetrack.garmin.com/session/1d1d4f20-8a4f-46d0-b962-6bd5cd6ce9b3/token/6527B218E3A5E7B9F96D927ADCFBA7" title="Follow Me" style="color:#fafafa; font-size:14px; font-family:'Open Sans', 'Lucida Grande', 'Lucida Sans Unicode', Helvetica, Arial, sans-serif; text-decoration:none; line-height:150%; -webkit-border-radius:10px; -moz-border-radius:10px; border-radius:10px;">
                                Watch My Live Activity
                              </a>
                            </td>
                          </tr>
                          <tr> <!-- Spacing -->
                            <td height="4"></td>
                          </tr>
                        </table>
                      </td>
                    </tr>
                  </table>
                </td>
              </tr>
            </table>
          </td>
        </tr>
      </table>
    </td>
  </tr>
</table>

<table width="100%" bgcolor="#0a1f2e" cellpadding="0" cellspacing="0" border="0" class="wrapperTable"> <!-- Footer wrapper -->
  <tr>
    <td>
      <table width="540" align="center" bgcolor="#fafafa" cellpadding="0" cellspacing="0" border="0" style="min-width:580px;" class="devicewidth-outer"> <!-- Style Bar -->
        <tr> <!-- Spacing -->
          <td height="36"></td>
        </tr>
      </table>
              <table width="580" align="center" bgcolor="11a9ed" cellpadding="0" cellspacing="0" border="0" style="min-width:580px;" class="devicewidth-outer"> <!-- Style Bar -->
        <tr>
          <td height="20" style="min-width:280px"></td>
        </tr>
      </table>
              <table width="580" align="center" cellpadding="0" cellspacing="0" border="0" style="min-width:580px;" class="devicewidth-outer"> <!-- Style Bar -->
        <tr> <!-- Spacing -->
          <td height="5"></td>
        </tr>
        <tr> <!-- Footer content -->
          <td align="left" style="font-family:'Open Sans', 'Lucida Grande', 'Lucida Sans Unicode', Helvetica, Arial, sans-serif; font-size:10px; color:#666666">
             <br />
             Please do not reply to this message. It was sent from a notification-only address that cannot accept incoming email. Find contact information on our <a href="http://www.garmin.com/contactUs/" style="color: #666">Contact Us</a> page.
             <br><br>
             Garmin respects your right to privacy and shares your concern about the security of any information you may submit. See our <a href="http://www.garmin.com/garmin/cms/lang/en/site/products/home/products-and-applications-privacy-statement" style="color: #666"> Privacy Policy</a> for more information.
             <br><br>
             &copy;2017 Garmin Ltd. or its subsidiaries. All rights reserved. Garmin International, 1200 E. 151st Street, Olathe, KS, 66062
          </td>
       </tr>
       <tr> <!-- Spacing -->
          <td height="10"></td>
       </tr>
      </table>
    </td>
  </tr>
</table>
<!--eo: template-->
</body>
</html>


